-- CreateEnum
CREATE TYPE "PROJECT_STATUS" AS ENUM ('IN_PROGRESS', 'COMPLETED', 'ARCHIVED', 'OVERDUE');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "status" "PROJECT_STATUS" NOT NULL DEFAULT 'IN_PROGRESS';
